services:

  phpapp:
    image: tejash727/sih-phpapp:latest
    container_name: phpapp
    restart: always

    ports:
      - "80:80"

    depends_on:
      - mysql
      - aiprediction
      - chatserver

    networks:
      - sih-network

  aiprediction:
    image: tejash727/sih-aiprediction:latest
    container_name: aiprediction
    restart: always

    ports:
      - "8001:8001"

    networks:
      - sih-network

  chatserver:
    image: tejash727/sih-chatserver:latest
    container_name: chatserver
    restart: always

    ports:
      - "8000:8000"

    networks:
      - sih-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sih
      MYSQL_ROOT_HOST: "%"

    command: --default-authentication-plugin=mysql_native_password

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql
      - ./Db_backup_files/sih_03-05-2026.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - sih-network

volumes:
  mysql-data:

networks:
  sih-network:
